name: CI

on:
  schedule:
    - cron: "30 15 * * *"
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Test
        run: python3 -m unittest discover -s test
      
      - name: Execute script on master branch
        if: github.ref == 'refs/heads/master'
        run: |
          chmod +x ./scripts/commit.py
          python3 ./scripts/commit.py
      
      - name: Build
        run: echo 'Configuration updated ...'

  post:
    always:
      - name: Clean workspace
        run: |
          echo 'This will always run'
          git clean -ffdx

    # You may need to replace the email notification with a GitHub action or another notification method
    failure:
      - name: Send email on failure
        run: |
          echo 'Sending email notification...'
          # You may need to replace this with the appropriate method for sending emails

    # GitHub Actions does not have built-in support for "unstable" or "changed" states
